import { ROLES } from "./roles.js";

export const PERMISSIONS = {
  MANAGE_USERS: "manage_users",

  MANAGE_TEAMS: "manage_teams",

  CREATE_INCIDENT: "create_incident",
  UPDATE_INCIDENT: "update_incident",
  DELETE_INCIDENT: "delete_incident",
  VIEW_INCIDENT: "view_incident",

  VIEW_ANALYTICS: "view_analytics",
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_TEAMS,

    PERMISSIONS.CREATE_INCIDENT,
    PERMISSIONS.UPDATE_INCIDENT,
    PERMISSIONS.DELETE_INCIDENT,
    PERMISSIONS.VIEW_INCIDENT,

    PERMISSIONS.VIEW_ANALYTICS,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.MANAGE_TEAMS,

    PERMISSIONS.CREATE_INCIDENT,
    PERMISSIONS.UPDATE_INCIDENT,
    PERMISSIONS.VIEW_INCIDENT,

    PERMISSIONS.VIEW_ANALYTICS,
  ],

  [ROLES.DEVELOPER]: [
    PERMISSIONS.CREATE_INCIDENT,
    PERMISSIONS.UPDATE_INCIDENT,
    PERMISSIONS.VIEW_INCIDENT,
  ],

  [ROLES.VIEWER]: [PERMISSIONS.VIEW_INCIDENT, PERMISSIONS.VIEW_ANALYTICS],
};
